# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Start from a Node.js base image
FROM node:22-alpine AS build

# Set the working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package.json /app/

# Install dependencies
RUN --mount=type=cache,target=/root/.npm npm install --ignore-scripts

# Copy the rest of the application code
COPY . /app

# Build the application
RUN npm run build

# Use a lightweight Node.js image for the final stage
FROM node:22-alpine AS runtime

# Set the working directory
WORKDIR /app

# Copy only the build output and necessary files
COPY --from=build /app/build /app/build
COPY --from=build /app/package.json /app/package.json
COPY --from=build /app/package-lock.json /app/package-lock.json

# Install only production dependencies
RUN npm ci --omit=dev

# Run the MCP server
ENTRYPOINT ["node", "build/index.js"]
